version: '3'
services:
  #Administration Api
  promocode-factory-administration-api:
    build: src/Otus.Teaching.Pcf.Administration/
    container_name: 'promocode-factory-administration-api'
    restart: always
    ports:
      - "8091:80"
    depends_on: 
      - promocode-factory-administration-db

  promocode-factory-administration-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: promo
      MONGO_INITDB_ROOT_PASSWORD: promopass
    ports:
      - "27017:27017"


  #ReceivingFromPartner Api
  promocode-factory-receiving-from-partner-api:
    build: src/Otus.Teaching.Pcf.ReceivingFromPartner/
    container_name: 'promocode-factory-receiving-from-partner-api'
    restart: always
    ports:
      - "8084:8080"
    environment:
      - "ConnectionStrings:PromocodeFactoryReceivingFromPartnerDb=Host=promocode-factory-receiving-from-partner-db;Database=promocode_factory_receiving_from_partner_db;Username=postgres;Password=docker"
      - "IntegrationSettings:GivingToCustomerApiUrl=http://promocode-factory-giving-to-customer-api"    
      - "IntegrationSettings:AdministrationApiUrl=http://promocode-factory-administration-api"       
    depends_on: 
      - promocode-factory-receiving-from-partner-db
  #ReceivingFromPartner Db
  promocode-factory-receiving-from-partner-db:
    image: "postgres:16.2"
    container_name: 'promocode-factory-receiving-from-partner-db'
    restart: always 
    ports:
      - 5434:5432
    environment: 
      - POSTGRES_PASSWORD=docker
  
  #GivingToCustomer Api
  promocode-factory-giving-to-customer-api:
    build: src/Otus.Teaching.Pcf.GivingToCustomer/
    container_name: 'promocode-factory-giving-to-customer-api'
    restart: always
    ports:
      - "8085:8080"
    depends_on: 
      - promocode-factory-giving-to-customer-db
  #GivingToCustomer Db
  promocode-factory-giving-to-customer-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: promo_2_customer
      MONGO_INITDB_ROOT_PASSWORD: promo_2_customer_pass
    ports:
      - "27018:27017"
