
name: Build and Test

on:
  push:
    branches:
      - hw04


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: './homeworks/otus.teaching.promocodefactory.homework.unittests/src'
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - run: pwd
        working-directory: ${{env.working-directory}}
        
      - run: dotnet test  Otus.Teaching.PromoCodeFactory.UnitTests --no-build --verbosity normal
        working-directory: ${{env.working-directory}}
